language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE palette_picker_tests;' -U postgres
  - knex migriate:latest --env=test
  - knex seed:run --env=test
notifications:
  email: false